services:
  - type: web
    name: flask-ai-chatbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:10000 flask_app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
